# Dependencies
markdown:             redcarpet
highlighter:          pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:            pretty
relative_permalinks:  true

# Setup
title:                Slides
tagline:              'A slide deck template'
description:          'Slides: A slide deck template'
url:                  /
baseurl:              '/slides'
paginate:             5

# About/contact
author:
  name:               'Nate Goldman'
  url:                https://twitter.com/ungoldman

# Custom vars
version:              1.0.0

github:
  repo:               https://github.com/ngoldman/slides

# Extra
safe:                 true #replicate gh-pages env
timezone:             America/Los_Angeles
encoding:             utf-8
